version: '3'
services:
  develop:
    restart: always
    build: .
    container_name: 'develop'
    working_dir: '/home/src'
    tty: true
    volumes:
      - bundle:/usr/local/bundle
      - ${SRC_PATH}:/home/src
volumes:
  bundle:
